### ISSUE TITLE
Enhancement/Feature

### ISSUE THREAD

**Issue by ohqpr** [Mojito-Fivem/mojito_pdm#14] opened 2022-05-16 02:05 UTC
Hello! I noticed that you had closed someone's request for making a ESX version of this resource because it's "Not an issue" [#10](https://github.com/Mojito-Fivem/mojito_pdm/issues/10), here I am making a feature / enhancement request because bothering you in your private messages is not a option for me. I hope you take this into consideration, I know quite a few people who would like to use this resource but can't.

**Comment by Mojito-Fivem** [comment] 2022-05-16 07:12
Duplicate of #10

**Closed by Mojito-Fivem** 2022-05-16 07:12 UTC
Labels: duplicate, wontfix

**Comment by ohqpr** [comment] 2022-05-18 04:57
Converted myself, since you don't like helping the community. Appreciate you for being nothing but useless 👍🏽
